chore: fail when setup hasn't been built and committed (#165)
* chore: fail when setup hasn't been built and committed

* Update push.yml

* use git diff quiet

* don't use backticks in shell

* Update setup.js

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -26,4 +26,10 @@ jobs:
       - run: npm test
       - run: npm run build --if-present
       - run: git status --porcelain dist/setup.js
+      - name: check dist build
+        run: |
+          if ! git diff --quiet --exit-code dist/setup.js; then
+            echo "::error run 'npm run build' and commit the dist/setup.js file"
+            exit 1
+          fi
       - uses: codecov/codecov-action@v3
